Notifications Prototype
pieter-groenendijk/oose-library-management-system pull request #42
Opened 2024-12-07 21:43 UTC by pieter-groenendijk

Ik moet er zeker nog dingen voor doen, bijv. unit tests. Echter leek het mij verstandig om alvast wat te mergen zodat men ook weet wat de connectiepunten zijn tot nu toe.

2024-12-09 20:03 UTC, MarzSP requested changes

2024-12-10 19:57 UTC, Lderksen27 approved these changes

2024-12-12 09:53 UTC, MarzSP approved these changes

2024-12-12 17:50 UTC, pieter-groenendijk commented on application/src/main/java/com/github/pietergroenendijk/notifications/NotificationTask.java
Ik gebruik als het goed een `Account`? 

In de toekomst zal het inderdaad wel verstandig zijn om misschien de contact data los te halen van het `Account`. Het is verstandiger om dat bij een membership op te slaan en dan een connectie te hebben op het account (naar het primaire abonnement).

2024-12-12 17:53 UTC, merged